### ISSUE TITLE
checkClassVersion error in py3: (Need to update cetbuildtools to v7_15_01)

### ISSUE THREAD

**Issue by wesketchum** [LArSoft/larsoft#1]
Need to update cetbuildtools, as checkClassVersion doesn't exist in python3.

```
  File "/cvmfs/larsoft.opensciencegrid.org/products/cetbuildtools/v7_14_00/bin/checkClassVersion", line 353, in main
    filename = string.strip(filename)
AttributeError: module 'string' has no attribute 'strip'
```

Similar issue documented here: https://cdcvs.fnal.gov/redmine/issues/23946. Now fixed in cetbuildtools v7_15_01.

**Comment by knoepfel** [comment]
Thanks for the report, @wesketchum.  I don't believe LArSoft is intending on moving its issue-tracking to GitHub, but that is something that should be discussed, and I will bring it up with the SciSoft team.

**Comment by wesketchum** [comment]
Yeah, talked to Erica about this already: I've just made an issue in larsoft redmine too: https://cdcvs.fnal.gov/redmine/issues/23956

**Comment by greenc-FNAL** [comment]
Can this GitHub issue be closed?

**Comment by lgarren** [comment]
yes
